import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'

import Navbar from '@/components/layout/navbar/navbar'
import Sidebar from '@/components/layout/sidebar/sidebar'
import ModalProvider from '@/providers/modal-provider'
import SupabaseProvider from '@/providers/supabase-provider'

import '../styles/globals.css'

const mono = Roboto_Mono({
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '500', '600', '700'],
	style: ['normal', 'italic'],
	variable: '--font-rmono',
})

export const metadata: Metadata = {
	title: 'Pinterest',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={mono.className}>
				<SupabaseProvider>
					<ModalProvider />
					<div className='dark:bg-bgBodyDark bg-bgBody min-h-screen overflow-hidden'>
						<aside className='hidden md:flex md:fixed md:inset-y-0 z-20 md:w-72 h-full'>
							<Sidebar />
						</aside>
						<main className='md:pl-72'>
							<Navbar />
							{children}
						</main>
					</div>
				</SupabaseProvider>
			</body>
		</html>
	)
}
